server.port=8447
# PEM configuration (Spring Boot 3.2+)
server.ssl.certificate=classpath:server-b.crt
server.ssl.certificate-private-key=classpath:server-b.key
server.ssl.client-auth=need
server.ssl.trust-certificate=classpath:client.crt
