server.port=8444
# Inbound TLS for Client module
server.ssl.certificate=classpath:client.crt
server.ssl.certificate-private-key=classpath:client.key

# Outbound Trust for Client calling Server
client.ssl.trust-certificate=classpath:server-trust.crt
