server.port=8444
# Inbound TLS for Client module
server.ssl.certificate=classpath:client.crt
server.ssl.certificate-private-key=classpath:client.key

# Outbound Trust for Client calling Server-A and Server-B (combined PEM bundle)
client.ssl.trust-certificate=classpath:servers-trust.crt

# Server URLs
server-a.url=https://localhost:8446/hello
server-b.url=https://localhost:8447/hello
